language: c

install:
  - sudo apt-get -qq install clang-3.5
  - clang --version
  - git clone git://github.com/jedisct1/libsodium.git
  - (cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig)
  - curl http://www.digip.org/jansson/releases/jansson-2.7.tar.gz | tar xz
  - (cd jansson-2.7; ./configure; make check; sudo make install; sudo ldconfig)

before_script:
  - export CC=clang

script:
  - scons
  - ./bin/test-icecore
